### PR TITLE
45 stop test

### PR DESCRIPTION
**Pull request by levBagryansky**
Closing #45 and #12
#24 was already solved.
I implemented a test of `thread.stop` using `thread.is-running`.

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please have a look

**Comment by Graur** [comment]
@levBagryansky I think these changes are too small. You removed two `@todo`'s and add only one test. Looks weird to me

**Comment by levBagryansky** [comment]
@Graur I have already solvedd #24 in pull request #44 and have not removed

**Review by Graur — APPROVED** [review]

**Comment by levBagryansky** [comment]
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
