### PR TITLE
50 thread.start

### PR DESCRIPTION
**Pull request by levBagryansky**
#50 
Changed `thread.start` so now it returns the `thread`  instead of `TRUE`
Also now repeated `start` do nothing.

### CODE REVIEW

**Comment by levBagryansky** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@levBagryansky maybe it's better to rename it to `started` now?

**Comment by yegor256** [comment]
@levBagryansky in this case it's better to not return a thread at all. method name mean what the method returns.

**Comment by levBagryansky** [comment]
@yegor256 ok I'll rename it

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
