### PR TITLE
43 is running

### PR DESCRIPTION
**Pull request by levBagryansky**
Solving #43 
I implemeted `thread.is-running` that returns `TRUE` if the `thread` was started and still works.
We also need it to solve puzzle #45

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please review

**Review by Graur — APPROVED** [review]
@levBagryansky Looks good to me

**Comment by levBagryansky** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
