### PR TITLE
increased stack size

### PR DESCRIPTION
**Pull request by levBagryansky**
Closes: #77 

---

## PR-Codex overview
This PR adds a new configuration to the `maven-surefire-plugin` in the `pom.xml` file to set the stack size for tests.

### Detailed summary
- Added `stack-size` property to `pom.xml`
- Added `maven-surefire-plugin` with `argLine` configuration to set stack size for tests.

> ✨ Ask PR-Codex anything about this PR by commenting with `/codex {your question}`

### CODE REVIEW

**Comment by levBagryansky** [comment]
@Graur please take a look

**Review by Graur — APPROVED** [review]
@levBagryansky Good one
@yegor256 Please, have a look

**Comment by levBagryansky** [comment]
@yegor256 please check

**Comment by yegor256** [comment]
@rultor merge

**Pull request merged**
